-
  name: 'AjaxFormEndpoint'
  uriPattern: 'form/{language}/{presetName}/{formIdentifier}'
  defaults:
    '@package': 'ObisConcept.NeosAjaxForm'
    '@controller': 'AjaxForm'
    '@action': 'index'
    '@format': 'html'
  httpMethods: ['GET','POST']
