TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'ObisConcept.NeosAjaxForm': TRUE

    userInterface:
      translation:
        autoInclude:
          'ObisConcept.NeosAjaxForm': ['Main', 'NodeTypes/*']
