
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          ObisConcept.NeosAjaxForm:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        ObisConcept.NeosAjaxForm: true
